### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by juliendonck** [monadic-xyz/access-p2p#7]
- [x] Adding "18:30-20:30" after each of the curriculum lecture dates listed on the Homepage
- [x] Adding Kei (from Gnosis) to the curriculum on the Homepage
- [x] Adding a "Stay informed" box where people can submit their email (in the case that they might not be applicable for the program in Berlin but are interested in the program and the content). The subtext can read: "Are you interested in the program and content but not ready or able to participate? Sign up for updates from our organizers."
- [x] By the end of the week, I will complete a FAQ - and would like to have that be another page of the website. Is that groovy/possible?
